CREATE TABLE IF NOT EXISTS ratings
(
    rating_id   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rating_name varchar(40) NOT NULL
);

CREATE TABLE IF NOT EXISTS films
(
    film_id      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_name    varchar(40)  NOT NULL,
    description  varchar(200) NOT NULL,
    release_date date         NOT NULL,
    duration     varchar(10),
    rating_id    integer REFERENCES ratings (rating_id)
);

CREATE TABLE IF NOT EXISTS genres
(
    genre_id   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    genre_name varchar(40) NOT NULL
);

CREATE TABLE IF NOT EXISTS film_genres
(
    id       integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_id  integer REFERENCES films (film_id),
    genre_id integer REFERENCES genres (genre_id)
);

CREATE TABLE IF NOT EXISTS users
(
    user_id   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_name varchar(40),
    login     varchar(40) NOT NULL UNIQUE,
    email     varchar(40) UNIQUE,
    birthday  date
);

CREATE TABLE IF NOT EXISTS likes
(
    film_id integer REFERENCES films (film_id),
    user_id integer REFERENCES users (user_id),
    CONSTRAINT film_id_user_id_pk PRIMARY KEY (film_id, user_id)
);


CREATE TABLE IF NOT EXISTS friendships
(
    user_id   integer REFERENCES users (user_id),
    friend_id integer REFERENCES users (user_id),
    status    boolean NOT NULL,
    CONSTRAINT user_id_friend_id_pk PRIMARY KEY (user_id, friend_id)
);
